### ISSUE TITLE
SotW: choose some category templates for the demo, and make sure styling is complete

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#104]
For the SotW demo, we want to make sure some of the category archives that are navigable from the cat menu (such as [development](https://wordpress.org/news-test/category/development/) and [security](https://wordpress.org/news-test/category/security/)) are complete and well tested. This is an outline of the tasks needed:

- [ ] Check all of the category archive views by navigating from the category menu
- [ ] Make a list of the ones that could feasibly be complete in time for the demo
- [ ] Open new issues for any problems or missing styling in those category views
- [ ] Make a list of the ones that won't be complete in time
- [ ] Disable the links to those incomplete categories in the menu
- [ ] Test and make sure all the clickable categories work well once the issues are closed

**Comment by tellyworth** [comment]
As with #98, we need some choices here so I'll suggest a list that we can whittle down to 2 or 3 worth showing off:

https://wordpress.org/news-test/category/security/ (missing the drop cap but otherwise ok?)
https://wordpress.org/news-test/category/development/ (ditto)
https://wordpress.org/news-test/category/uncategorized/ (and other non-special categories)
https://wordpress.org/news-test/?s=wordpress
https://wordpress.org/news-test/2021/ (date archive)

**Comment by tellyworth** [comment]
Now that #81 is merged we could consider polishing up the month-in-wordpress category view:

https://wordpress.org/news-test/category/month-in-wordpress/

**Comment by tellyworth** [comment]
@kellychoffman likewise, this could use some design decisions and sharp eyes.
