### ISSUE TITLE
Launch tasks

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#251]
### Before launch

- [x] draft announcement post. ask for feedback. where to publish? xpost to relevant p2s.
- [x] tweet about it coming next week
- [x] notify `#teamreps` `#design` `#meta` channel that launch will happen soon
- [x] specifically notify Make Marketing as well as Community and Core (in their meetings)
- [x] maybe do some beta testing w/ contributors?
- [x] Green light from Neso (clear to launch on tech issues)
- [x] Green light from Design (clear to launch on design completion)
- [x] Green light from Navigators (announcements, timing)

### Launch day

- [x] one last final 👍 from @beafialho 
- [x] sync svn from git, deploy
- [x] Activate the new theme on the production site
- [x] Update Reading settings to have static home and posts pages
- [x] Activate gutenberg on production site? done but [deactivated](https://github.com/WordPress/wporg-mu-plugins/issues/92#issuecomment-1019688072) and re-activated.
- [x] update [news ID in `save_dependent_global_styles`](https://github.com/WordPress/wporg-mu-plugins/blob/11225d2d5f895414f40904c169a66f882cb8113a/mu-plugins/blocks/global-header-footer/blocks.php#L907) when activating news theme. use `WPORG_NEWS_BLOGID`
- [x] Remove the preview toggle code in `mu-plugins/main-network/site-news.php`
- [x] publish announcement post
- [x] marketing markets post

### Clean up

- [x] make sure no code is referring to w.org/news-test anymore
- [x] delete w.org/news-test ?
    - [x] if so, remove temporary News link in `get_menu_url_for_current_page()`

please add more items if you think of anything else

**Comment by tellyworth** [comment]
I'd add these as prerequisites for launch:

* Green light from Neso (clear to launch on tech issues)
* Green light from Design (clear to launch on design completion)
* Green light from Navigators/Marketing? (clear to launch on externals, timing, announcements etc)

**Comment by kellychoffman** [comment]
Announcement post draft: https://docs.google.com/document/d/1xxyOa8rc7mctXU_RQpZ-SRW6rjIRYFV0Y6qgP_lhJLI/edit
