### ISSUE TITLE
Add artistic content to left column

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#75]
The content here isn't essential for the launch, and isn't straightforward to implement w/ the current state of FSE.

- [x] Releases category: version number the post is about, like described in #38 
- [ ] Events category: year of post. The year is simple with `<!-- wp:post-date {"level":2,"className":"event-year","format":"Y"} /-->`, but it needs to be grouped according to year, which isn't simple. #281 
- [x] All categories without a specific template: The first letter of the category name, with other letters hidden. This could be done in CSS with `color` and `:first-letter`, but that's hacky. [Dynamic templates](https://github.com/WordPress/gutenberg/issues/32939) would probably be best. A custom block would also work, but that isn't a sustainable approach for all the other instances where we need dynamic templates.
- [ ] The 2-column layout styles may need to be adjusted to account for all of the above

**Comment by ryelle** [comment]
Do we need this separate tracking issue? Releases & the initial letters are done, and Events is tracked in #281.

**Comment by iandunn** [comment]
Doesn't seem like it, now that those issues exist 👍🏻
