### ISSUE TITLE
Gutenberg: Remove misc workarounds

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#79]
### dynamic templates

There are a bunch of tickets that are [blocked](https://github.com/WordPress/wporg-news-2021/labels/blocked%3A%20external) on Gutenberg not supporting [dynamic templates](https://github.com/WordPress/gutenberg/issues/32939). 

Here are some more things that aren't big enough to warrant their own issue.

- [ ] Reduce the "Latest Release" title on the homepage to just the version number, rather than the full title (similar to #75)
- [ ] Month in WP: Remove PHP classes and replace with a more straightforward solution https://github.com/WordPress/wporg-news-2021/pull/81#discussion_r754774886
- [ ] Create a constant for home `perPage`, so it can be DRY between `functions.php` and `latest-posts` template part
- [ ] extra post classes, conditional template parts, etc from #88. see https://github.com/WordPress/wporg-news-2021/pull/88#discussion_r757648019

### other
- [ ] remove `custom_query_block_attributes ()` if https://github.com/WordPress/gutenberg/issues/36785 and other dependencies are solved
- [ ] move to corresponding Core functions in `get_rosetta_custom_menu_items()` etc
