### ISSUE TITLE
Implement design for "pages" (archives)

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#8]
https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A8683

This will probably need to be broken out into individual issues as they're started. Some already are.

### misc
- [x] homepage #18
- [x] rough markup for `page` post type - #49 , #51 
- [x] date, tag, author archives - why aren't they falling back to index.html?
- [x] 404 - rough markup - #51 
- [x] #129

### categories - standard markup
- [x] all posts / latest posts
- [x] rough markup for uncategorized, security, development - #51 
- [x] #78

### categories - unique markup
- [x] releases #51, #38
- [x] events (similar to releases) - rough markup
- [x] events (similar to releases) - final markup and CSS
- [x] #76
- [ ] community - final markup and CSS
- [x] #77
- [ ] month in wp - final markup and CSS
- [ ] podcast - rough markup (design still in flux as of nov 10)
- [x] #130

**Comment by iandunn** [comment]
closing because everything left here has individual issues now
