### ISSUE TITLE
State of the Word preview

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#83]
This is an overview of [the milestone](https://github.com/WordPress/wporg-news-2021/milestone/6). The goal is to get critical parts of the site ready to demo at the State of the Word. New issues can be broken off of here when necessary.

### Desktop:

1. open browser, maximize it (should be `1320px` wide)
1. open w.org/news-test
1. open local nav categories dropdown
1. close local nav categories dropdown
1. scroll down to "latests posts" section
1. click on a post (pick one a specific one few days before)
1. scroll through that post

### Mobile:

1. click "News" in local nav bar to go back to homepage
1. open DevTools
1. click responsive mode button
1. Choose `?` from the menu (should be `375px` wide)
1. Scroll through homepage and single post like you did for mobile

There won't be any interactions with global search, hover states, clicking any other links, etc. it's just the the visual aspects of the above that we're concerned with

### Visual Polish
The following templates need to be visually polished to match [the mockup](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A8682). They don't need to be any more functionally complete than they already are, though.

- [ ] global header - #86
- [ ] local header - #86, #90
- [x] #96
    - [x] people of wp images flex layout needs to fill width at all viewports - maybe use something similar to "priority navigation" from #86
    - [x] Enable subscription #35
    - [x] Add podcast icons directly to theme for now, see #36 
- [x] #97
     - [x] Hide likes/sharing if #24 isn't done in time
- [x] #98
- [x] #100
- [x] #101
- [x] #102

### Additional tasks:

- [x] import content #82 
- [x] import new posts the friday before the event, so that posts match production
- [ ] sync production w/ latest code as needed

### Demo video

The demo is to be pre-recorded (by who?)

- [ ] Refine the exact sequence of clicks and views based on above (including decisions about which posts and categories to show)
- [ ] Write a script
- [ ] Record a test video
- [ ] Check the video closely and raise issues for anything that needs fixing or refining
- [ ] Record the final video
