### ISSUE TITLE
Implement design for posts & content

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#9]
https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A8682

each of these should have it's own PR (and an issue too, if needed)

### full width (default)

- [x] grid + structure
- [x] short
- [x] medium
- [x] long
- [x] podcast
- [x] month in wp
- [ ] short pullquote https://github.com/WordPress/wporg-news-2021/issues/353
- [ ] large pullquote https://github.com/WordPress/wporg-news-2021/issues/353
- [ ] images https://github.com/WordPress/wporg-news-2021/issues/354
- [x] content width alignment

### content width

- [x] alignment
- [ ] verse https://github.com/WordPress/wporg-news-2021/issues/353
- [ ] quote https://github.com/WordPress/wporg-news-2021/issues/353

### blocks

- [x] audio player
- [ ] quote 1 https://github.com/WordPress/wporg-news-2021/issues/353
- [ ] quote 2 https://github.com/WordPress/wporg-news-2021/issues/353
- [ ] verse https://github.com/WordPress/wporg-news-2021/issues/353
- [x] code
- [ ] contributors break 1 https://github.com/WordPress/wporg-news-2021/issues/355
- [ ] contributors break 2 https://github.com/WordPress/wporg-news-2021/issues/355
- [ ] contributors break 3 https://github.com/WordPress/wporg-news-2021/issues/355

**Comment by coreymckrill** [comment]
@iandunn I'm trying to figure out how many of these checklist items still need to be done, but I'm not sure what some of them are referring to:

* `content width alignment` - is this a specific block or just the fact that the content column is supposed to be on the right side on desktop widths? If the latter, I think this one is done, right?
* `contributors break 1`, `2`, `3` - what are these referring to?

**Comment by iandunn** [comment]
IIRC they were all phrases used in the mockup

> content width alignment

https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A11896

> contributors break 1, 2, 3 

https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4764%3A24504

**Comment by coreymckrill** [comment]
> full width images

Captions were addressed in https://github.com/WordPress/wporg-news-2021/pull/275, ensuring that existing posts use the full-width alignment is more of a [content issue](https://github.com/WordPress/wporg-news-2021/issues/354).

**Comment by coreymckrill** [comment]
Ok, the remaining checklist items above fit into three issues, which have all now been created. I'm going to close this to declutter the milestone.
